version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # Agregar Node.js flags para soporte ESM
      - NODE_OPTIONS=--experimental-vm-modules --experimental-specifier-resolution=node
      # Configurar conexión a Redis usando el nombre del servicio
      - REDIS_HOST=redis
    restart: always

  mongodb:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data: 