services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./.env:/app/.env
    command: npm run dev
    stop_signal: SIGINT
    restart: "no"
    init: true

volumes:
  mongodb_data:
  redis_data: 